application: jugglethis-wikiblog
version: live
runtime: python
api_version: 1

builtins:
- datastore_admin: on

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 )$


handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: deferred.py
  login: admin

- url: /admin/.*
  script: admin.py
  login: admin
  
- url: /user
  script: user.py
  
- url: /user/.*
  script: user.py
  login: required

- url: /static/([^/]+)/(.*)
  static_files: themes/\1/static/\2
  upload: themes/[^/]+/static/.*

- url: /favicon.ico
  static_files: static/default/favicon.ico
  upload: themes/default/static/favicon.ico

- url: /.*
  script: static.py
